### PR TITLE
Pass github options to API instance.

### PR DESCRIPTION
**Pull request by milesj**
Solves https://github.com/ericclemmons/github-semantic-version/issues/19

@ericclemmons

### CODE REVIEW

**Comment by ericclemmons** [comment]
@milesj You are now a collaborator on both GitHub & NPM!

```
 ❯ npm owner add milesj
+ milesj (github-semantic-version)
 ❯ npm owner ls
milesj <mileswjohnson@gmail.com>
daveashworth <dca.account@gmail.com>
poeticninja <saul.maddox@gmail.com>
ericclemmons <eric@smarterspam.com>
```

**Comment by milesj** [comment]
Awesome! Thanks for the quick turn around and contribution add.

**Comment by milesj** [comment]
@ericclemmons Sorry to bother but it looks like the auto-deploy from within Travis failed. Shall I run the command locally to publish the new version?

**Comment by ericclemmons** [comment]
That’s perfectly fine!




On November 9, 2017 at 4:39:22 PM, Miles Johnson (notifications@github.com)
wrote:

@ericclemmons <https://github.com/ericclemmons> Sorry to bother but it
looks like the auto-deploy from within Travis failed. Shall I run the
command locally to publish the new version?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ericclemmons/github-semantic-version/pull/20#issuecomment-343315411>,
or mute the thread

**Pull request merged**
